### ISSUE TITLE
Consider  issues from Deepsource to be implemented

### ISSUE THREAD

**Issue by Mr-emeka** [despensa-app/web#3]
Hello @despensa-app, I have uploaded an image from deepsource would love to work on some of these issues as part of my contribution to open source. Also would ask that you consider these issues for hacktoberfest.

[Deepsource Link](https://deepsource.io/gh/despensa-app/web/issues?category=recommended&analyzer=all)

![image](https://user-images.githubusercontent.com/30534680/137270067-cd789f19-a153-487b-8a63-4463a22807a8.png)

**Comment by nmarulo** [comment]
Duplicate of #2
